default: &local_defaults
  adapter: postgresql
  host: localhost
  encoding: utf8
  username: postgres
  pool: 5
  min_messages: ERROR

development:
  <<: *local_defaults
  database: death_star_sensor_development 

test:
  <<: *local_defaults
  database: deat_star_sensor_test
production:
  <<: *local_defaults
  database: death_star_sensor_production
